### ISSUE TITLE
“longest flow path”cannot get the result

### ISSUE THREAD

**Issue by 2179856994** [lymperis-e/Geomeletitiki-Watershed-Analysis-Toolbox---QGIS-Plugin-#2]
hello,I donot know why I failed and get this result below when I run the "longest flow path":

 Traceback (most recent call last):
File "D:/QGIS3~1.16/apps/qgis-ltr/./python/plugins\processing\algs\qgis\PointDistance.py", line 137, in processAlgorithm
matType, nPoints, feedback)
File "D:/QGIS3~1.16/apps/qgis-ltr/./python/plugins\processing\algs\qgis\PointDistance.py", line 204, in linearMatrix
outID = outFeat[outIdx]
KeyError: '-1'

The discharge point has been moved on the channel network and the discharge point has a unique integer field before I run it. What should I do to solve this problem? Thank you every much.

**Comment by lymperis-e** [comment]
Hey, sorry to be so late to this. You closed the issue, did you solve the problem? May I ask, did you use a projected CRS?

**Comment by 2179856994** [comment]
I am very happy to recieve your reply! Yes,I use a projected CRS. I find the stream must get by the "Geomeletitiki hydrology analysis"——“1. Filled DEM & Channel Network”,then it can get a result. in the first i use a network got from other tool. i guess the reason is the streamorder field use shreve order. do the shreve order is required to define the longest path in your code?I get the result by this way,but i am confused because the path isnot from the pourpoint and i donot get the result every time.
