### ISSUE TITLE
Error: Algorithm saga:catchmentarea not found

### ISSUE THREAD

**Issue by forestcomber** [lymperis-e/Geomeletitiki-Watershed-Analysis-Toolbox---QGIS-Plugin-#3]
Thank-you for making this plugin !

I have a standard install of QGIS 3.24.1 on Windows 11.

I am getting this error when running algorithm 1 : 

Error: Algorithm saga:catchmentarea not found

Error: Algorithm saga:catchmentarea not found

Execution failed after 494.28 seconds (8 minutes 14 seconds)

QGIS version: 3.24.1-Tisler
QGIS code revision: 5709b824
Qt version: 5.15.2
Python version: 3.9.5
GDAL version: 3.4.1
GEOS version: 3.10.2-CAPI-1.16.0
PROJ version: Rel. 8.2.1, January 1st, 2022
PDAL version: 2.3.0 (git-version: 9f35b7)
Algorithm started at: 2022-03-24T09:50:27
Algorithm '1. Filled DEM & Channel Network' starting…

**Comment by lymperis-e** [comment]
Forest, thank you for your feedback! This is a known problem, and has to do with the SAGA version that comes with QGIS. Up until recently, both the standalone QGIS installer, and the OSGeo4W package shipped with SAGA v. 2.3.2 (which is the Long Term Support version). Newer packages ship with SAGA v.7.8.2, in which most of the algorithms have been renamed and slightly modified. The current plugin has been developed against this older version of SAGA, and thus calls its algorithms via their old names. The solution here is to install a package of QGIS with SAGA v.2.3.2. I hope to find some time to make the plugin compatible with both distributions of SAGA, but unfortunately this is gonna take some time

**Comment by forestcomber** [comment]
Thank-you, I really appreciate your reply ! Does it matter if they are v.2.3.2 32 or 64 bit binaries ? Envoyé à partir de Courrier pour Windows De : lymperis-eEnvoyé le :March 24, 2022 11:17À : lymperis-e/Geomeletitiki-Watershed-Analysis-Toolbox---QGIS-Plugin-Cc : forestcomber; AuthorObjet :Re: [lymperis-e/Geomeletitiki-Watershed-Analysis-Toolbox---QGIS-Plugin-] Error: Algorithm saga:catchmentarea not found (Issue #3) Forest, thank you for your feedback! This is a known problem, and has to do with the SAGA version that comes with QGIS. Up until recently, both the standalone QGIS installer, and the OSGeo4W package shipped with SAGA v. 2.3.2 (which is the Long Term Support version). Newer packages ship with SAGA v.7.8.2, in which most of the algorithms have been renamed and slightly modified. The current plugin has been developed against this older version of SAGA, and thus calls its algorithms via their old names. The solution here is to install a package of QGIS with SAGA v.2.3.2. I hope to find some time to make the plugin compatible with both distributions of SAGA, but unfortunately this is gonna take some time—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by lymperis-e** [comment]
SAGA Next Gen is now the underlying processing provider. See #5
